name: Testing - Reusable Workflow
on: 
  ??????????
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: '${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}'
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live
